### ISSUE TITLE
Issue : zip object does not have a sort method

### ISSUE THREAD

**Issue by RemiCuxac** [peerke88/SkinningTools#2]
https://github.com/peerke88/SkinningTools/blob/3b2ed095f7dcfef64166acc9fec20392cc5fd151/Maya/tools/mathUtils.py#L308C10-L308C10

I think it should be :
``iter = list(zip(nodes, points))``
Because zip object does not have a sort method.

**Comment by peerke88** [comment]
should be fixed in commit 290 following @trevorvanhoof 's advice:
https://github.com/peerke88/SkinningTools/commit/6cea42e251a5d4715e942db65778807e44f61412
